[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"] 

[phases.build]
cmds = ["cd backend && pip install groq -r requirements.txt"]

[phases.start]
cmds = ["cd backend && gunicorn app:app"]