[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = [
  "cd backend",
  "nix-shell --packages python311 --command 'export PYTHONPATH=$(pwd); python3 -m venv venv; source venv/bin/activate; pip install -r requirements.txt'"
]

[phases.start]
cmds = ["cd backend && source venv/bin/activate && gunicorn app:app"]