[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.build]
cmds = [
  "cd backend",
  "nix-shell -p python311 python311Packages.pip --run 'export NIX_PATH=$NIX_PATH:. && pip install -r requirements.txt'"
]

[phases.start]
cmds = ["cd backend && gunicorn app:app"]