[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.gunicorn", "python311Packages.flask"]

[phases.build]
cmds = []

[phases.start]
cmds = ["source /etc/profile && cd backend && gunicorn app:app"]