[phases.setup]
nixPkgs = ["python311", "python311Packages.virtualenv"]

[phases.build]
cmds = [
  "cd backend",
  "python3 -m venv venv",
  ". venv/bin/activate && pip install -r requirements.txt"
]

[phases.start]
cmds = ["cd backend && . venv/bin/activate && gunicorn app:app"]